spring:
  config:
    activate:
      on-profile: "qa"


build:
  version: "2.0"
#defalt=3.0, qa=2.0 and prod=1.0
accounts:
  message: "Welcome to TravelBank accounts related QA APIs "
  contactDetails:
    name: "dinesh - QA Lead"
    email: "dinesh@travelbank.com"
  onCallSupport:
    - (444) 515-1234
    - (555) 523-4345
