#localhost:8080/h2-console--for access h2 database
#web-allow-others: true — allows access from outside localhost (remote connections),
#when it is uploded in docker.
server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "prod"
      
build:
  version: "3.0"
#defalt=3.0, qa=2.0 and prod=1.0
accounts:
  message: "Welcome to TravelBank accounts related local APIs "
  contactDetails:
    name: "Vinay Teja - Developer"
    email: "vinay@travelbank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
